services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://pos-6k7w.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d2tq71je5dus73e37g70-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: pos_015a
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: KVQrhyMhyIzbkUmpJyu9q73kLcS8N0Jr
      - key: DB_SSLMODE
        value: require
    releaseCommand: "php artisan migrate:fresh --force"
